# Generated by Django 5.2.8 on 2025-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('soup', 'Супи'), ('salad', 'Салати'), ('main_course', 'Основные блюда'), ('dessert', 'Десерти'), ('beverage', 'Напої')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
