# Generated by Django 5.2.8 on 2025-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_dish_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
