# Generated by Django 5.2.8 on 2025-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
