# Generated by Django 5.2.8 on 2025-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_dish_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('cash', 'Готівка'), ('card', 'Карта')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('soup', 'Супи'), ('salad', 'Салати'), ('main_course', 'Основні блюда'), ('dessert', 'Десерти'), ('beverage', 'Напої')], max_length=50),
        ),
    ]
