# Generated by Django 5.2.8 on 2025-11-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_dish_rating_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes_photos/'),
        ),
    ]
