# Generated by Django 5.2.8 on 2025-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0007_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
