# Generated by Django 5.2.8 on 2025-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0008_dish_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='simelions',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
