# Generated by Django 5.2.8 on 2026-01-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
