# Generated by Django 5.2.8 on 2026-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0011_rename_total_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('in_progress', 'В процесі'), ('completed', 'Завершене'), ('canceled', 'Скасоване')], default='new', max_length=20),
        ),
    ]
